import { createFileRoute } from "@tanstack/react-router";
import { Boxes, Brush, MessageSquareText, MonitorSmartphone } from "lucide-react";
import { PageHero } from "@/components/PageHero";
const groups=[
  {icon:MonitorSmartphone,title:"UI/UX",level:"Advanced",items:["User-centred design","UX research","Wireframing & prototyping","UI design","Design systems"]},
  {icon:Brush,title:"Visual craft",level:"Advanced",items:["Brand identity","Packaging","Print & poster design","Campaign creatives","Visual communication"]},
  {icon:Boxes,title:"Tools",level:"Daily practice",items:["Figma","Adobe Photoshop","Adobe Illustrator","Adobe InDesign","Adobe XD","Canva","Miro","Affinity"]},
  {icon:MessageSquareText,title:"Training",level:"35+ students",items:["Workshop facilitation","Curriculum development","Mentorship","Client communication","English & Tamil"]},
];
export const Route=createFileRoute("/skills")({head:()=>({meta:[{title:"Skills — Desigan M."},{name:"description",content:"UI/UX, graphic design, visual communication, design tools, training and mentoring skills."},{property:"og:title",content:"Skills — Desigan M."},{property:"og:description",content:"Design craft, tools, systems and teaching capabilities."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Skills});
function Skills(){return <><PageHero><p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">Capability map</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-bold leading-tight md:text-7xl">Thinking, making and teaching design.</h1></PageHero><section className="px-6 py-24"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-2">{groups.map((group,index)=><article key={group.title} className={`${index===3?"bg-pastel-lilac":index===1?"bg-coral/20":index===0?"bg-accent-soft":"bg-card"} group rounded-md border border-ink/10 p-7 transition-all hover:-translate-y-1 hover:shadow-xl`}><div className="flex items-center justify-between"><group.icon className="size-7 transition-transform group-hover:rotate-6 group-hover:scale-110"/><span className="rounded-full border border-ink/15 px-3 py-1 text-[10px] font-bold uppercase">{group.level}</span></div><h2 className="mt-12 font-display text-3xl font-bold">{group.title}</h2><div className="mt-7 flex flex-wrap gap-2">{group.items.map((item)=><span key={item} className="rounded-full border border-ink/15 bg-surface/60 px-3 py-2 text-xs font-medium transition-colors hover:bg-ink hover:text-surface">{item}</span>)}</div></article>)}</div></section></>}
