/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as GraphicDesignRouteImport } from './routes/graphic-design'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as UiUxProjectsRouteImport } from './routes/ui-ux-projects'
import { Route as WorkProjectIdRouteImport } from './routes/work.$projectId'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicDesignRoute = GraphicDesignRouteImport.update({
  id: '/graphic-design',
  path: '/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const UiUxProjectsRoute = UiUxProjectsRouteImport.update({
  id: '/ui-ux-projects',
  path: '/ui-ux-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkProjectIdRoute = WorkProjectIdRouteImport.update({
  id: '/work/$projectId',
  path: '/work/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/skills': typeof SkillsRoute
  '/training': typeof TrainingRoute
  '/ui-ux-projects': typeof UiUxProjectsRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/skills': typeof SkillsRoute
  '/training': typeof TrainingRoute
  '/ui-ux-projects': typeof UiUxProjectsRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/skills': typeof SkillsRoute
  '/training': typeof TrainingRoute
  '/ui-ux-projects': typeof UiUxProjectsRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/graphic-design'
    | '/skills'
    | '/training'
    | '/ui-ux-projects'
    | '/work/$projectId'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/graphic-design'
    | '/skills'
    | '/training'
    | '/ui-ux-projects'
    | '/work/$projectId'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/graphic-design'
    | '/skills'
    | '/training'
    | '/ui-ux-projects'
    | '/work/$projectId'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  GraphicDesignRoute: typeof GraphicDesignRoute
  SkillsRoute: typeof SkillsRoute
  TrainingRoute: typeof TrainingRoute
  UiUxProjectsRoute: typeof UiUxProjectsRoute
  WorkProjectIdRoute: typeof WorkProjectIdRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic-design': {
      id: '/graphic-design'
      path: '/graphic-design'
      fullPath: '/graphic-design'
      preLoaderRoute: typeof GraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-ux-projects': {
      id: '/ui-ux-projects'
      path: '/ui-ux-projects'
      fullPath: '/ui-ux-projects'
      preLoaderRoute: typeof UiUxProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$projectId': {
      id: '/work/$projectId'
      path: '/work/$projectId'
      fullPath: '/work/$projectId'
      preLoaderRoute: typeof WorkProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  GraphicDesignRoute: GraphicDesignRoute,
  SkillsRoute: SkillsRoute,
  TrainingRoute: TrainingRoute,
  UiUxProjectsRoute: UiUxProjectsRoute,
  WorkProjectIdRoute: WorkProjectIdRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
