/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as UiUxProjectsRouteImport } from './routes/ui-ux-projects'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkProjectIdRouteImport } from './routes/work.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const UiUxProjectsRoute = UiUxProjectsRouteImport.update({
  id: '/ui-ux-projects',
  path: '/ui-ux-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkProjectIdRoute = WorkProjectIdRouteImport.update({
  id: '/work/$projectId',
  path: '/work/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/ui-ux-projects': typeof UiUxProjectsRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/ui-ux-projects': typeof UiUxProjectsRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/ui-ux-projects': typeof UiUxProjectsRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/skills'
    | '/ui-ux-projects'
    | '/work/$projectId'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/skills'
    | '/ui-ux-projects'
    | '/work/$projectId'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/skills'
    | '/ui-ux-projects'
    | '/work/$projectId'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  SkillsRoute: typeof SkillsRoute
  UiUxProjectsRoute: typeof UiUxProjectsRoute
  WorkProjectIdRoute: typeof WorkProjectIdRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-ux-projects': {
      id: '/ui-ux-projects'
      path: '/ui-ux-projects'
      fullPath: '/ui-ux-projects'
      preLoaderRoute: typeof UiUxProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$projectId': {
      id: '/work/$projectId'
      path: '/work/$projectId'
      fullPath: '/work/$projectId'
      preLoaderRoute: typeof WorkProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  SkillsRoute: SkillsRoute,
  UiUxProjectsRoute: UiUxProjectsRoute,
  WorkProjectIdRoute: WorkProjectIdRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
